"""Generate a complete, hashed file inventory and a first-party source index."""

from __future__ import annotations

import argparse
import hashlib
import json
import subprocess
from collections import Counter
from pathlib import Path


def inventory(source: Path, destination: Path) -> None:
    paths = (
        subprocess.check_output(["git", "ls-files", "-z"], cwd=source)
        .decode()
        .split("\0")
    )
    revision = subprocess.check_output(
        ["git", "rev-parse", "HEAD"], cwd=source, text=True
    ).strip()
    files = []
    for name in sorted(filter(None, paths)):
        path = source / name
        if not path.is_file():
            raise ValueError(f"Tracked file missing: {name}")
        vendor = any(part in name for part in ("marsbar-", "/xlwrite/", "/sort_nat.m"))
        kind = "vendor" if vendor else "source" if path.suffix == ".m" else "asset"
        files.append(
            dict(
                path=name,
                kind=kind,
                bytes=path.stat().st_size,
                sha256=hashlib.sha256(path.read_bytes()).hexdigest(),
            )
        )
    destination.mkdir(parents=True, exist_ok=True)
    (destination / "legacy-files.json").write_text(
        json.dumps(dict(schema_version=1, revision=revision, files=files), indent=2)
        + "\n"
    )
    counts = Counter(row["kind"] for row in files)
    lines = [
        "# MATLAB file inventory",
        "",
        f"Baseline: `{revision}`.",
        "",
        f"Tracked files: {len(files)}. Classification: {dict(counts)}.",
        "",
        "Generated by `tools/inventory_legacy.py`; every tracked file has a SHA-256",
        "in `legacy-files.json`. Classification identifies known vendor directories;",
        "it does not establish authorship or whether a function is reachable.",
        "",
        "## First-party source candidates",
        "",
        "| Source | Work package |",
        "| --- | --- |",
    ]
    for row in files:
        if row["kind"] == "source":
            name = str(row["path"])
            wp = "WP3b / WP2" if "Coregistration" in name else "WP3a / WP2"
            lines.append(f"| `{name}` | {wp} |")
    lines += ["", "## Non-source assets", "", "| Asset | Bytes |", "| --- | --- |"]
    for row in files:
        if row["kind"] == "asset":
            lines.append(f"| `{row['path']}` | {row['bytes']} |")
    (destination / "legacy-inventory.md").write_text("\n".join(lines) + "\n")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("source", type=Path)
    parser.add_argument("destination", type=Path)
    args = parser.parse_args()
    inventory(args.source, args.destination)
